export { default as About } from './About';
export { default as App } from './App';
export { default as Contact } from './Contact';
export { default as Header } from './Header';
export { default as Home } from './Home';
export { default as Nav } from './Nav';
export { default as Portfolio } from './Portfolio';
export { default as SingleProject } from './SingleProject';
export { default as SingleSkill } from './SingleSkill';